Enhance getengage.sh to set default source directory and manage OpenSSL libraries. Update Makefile to support static linking and improve dependency handling. Modify win.nmake for static library usage.

diff --git a/samples/c/mingage/Makefile b/samples/c/mingage/Makefile
--- a/samples/c/mingage/Makefile
+++ b/samples/c/mingage/Makefile
@@ -4,10 +4,12 @@
 
 CC := gcc
 CXX := g++
-CFLAGS := -Wall -std=c++11 -fPIC 
-#CFLGAS += -Wno-psabi
-VER := 1.255.9095
-ENGAGE_LINE := interim
+CFLAGS := -Wall -std=c++11
+#CFLAGS += -Wno-psabi
+# Engage engine version: required for depend/depends (see getengage.sh). Example:
+#   make depend VER=1.255.9095
+#   make depend VER=1.255.9095 ENGAGE_LINE=interim
+ENGAGE_LINE ?= interim
 
 ifeq ($(DEBUG), 1)
     CFLAGS += -DDEBUG -O0 -ggdb
@@ -18,45 +20,46 @@ endif
 UNAME_S := $(shell uname -s | tr A-Z a-z)
 ARCH := $(shell uname -p | tr A-Z a-z)
 
-ifeq ($(UNAME_S), darwin)
-	LIBNAME=libengage-shared.dylib
-else ifeq ($(ARCH), x86_64)
-	LIBNAME=libengage-shared.so
-else ifeq ($(ARCH), aarch64)
-	LIBNAME=libengage-shared.so
-endif
-
-INCLUDES =  -I. -I./engage -I./engage/include
-LFLAGS = -L./engage
-
-LIBS = -lengage-shared -lpthread 
+INCLUDES = -I. -I./engage -I./engage/include
 SRCS = Mingage.cpp WorkQueue.cpp
 OBJS = $(SRCS:.cpp=.o)
 
 MAIN = mingage
 
-.PHONY: depend clean
+ENGAGE_LIB := ./engage/libengage-static-native.a
 
-all:    $(MAIN)	
+ifeq ($(UNAME_S),darwin)
+    ENGAGE_LIBS := $(ENGAGE_LIB) -lpthread \
+        -framework CoreFoundation \
+        -framework SystemConfiguration \
+        -framework CoreAudio \
+        -framework AudioToolbox \
+        -framework Security
+else
+    ENGAGE_LIBS := $(ENGAGE_LIB) -lpthread -ldl
+endif
 
-$(MAIN): $(OBJS) 
-	$(CXX) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(LFLAGS) $(LIBS)
-	@echo ""
-	@echo "****************************** IMPORTANT ******************************"
-	@echo "$(LIBNAME) has been placed in './engage'"
-	@echo "Be sure to 'export LD_LIBRARY_PATH=./engage' if your OS requires it or"
-	@echo "simply run as 'LD_LIBRARY_PATH=./engage ./mingage'."
-	@echo "***********************************************************************"
+.PHONY: depend depends clean
+
+all: $(MAIN)
+
+$(MAIN): $(OBJS) $(ENGAGE_LIB)
+	$(CXX) $(CFLAGS) $(INCLUDES) -o $(MAIN) $(OBJS) $(ENGAGE_LIBS)
 
 .cpp.o:
-	$(CXX) -c $(CFLAGS) $(INCLUDES) $<  -o $@
-
+	$(CXX) -c $(CFLAGS) $(INCLUDES) $< -o $@
+	
 clean:
 	${RM} *.o *~ $(MAIN)
 	${RM} -r engage
+	@mkdir -p engage
 
 depend: depends
 depends:
+	@if [ -z "$(strip $(VER))" ]; then \
+		echo >&2 "VER is required (Engage engine version). Example: make depend VER=1.255.9095 [ENGAGE_LINE=$(ENGAGE_LINE)]"; \
+		exit 1; \
+	fi
 	@./getengage.sh $(VER) $(ENGAGE_LINE)
-	
+
 # DO NOT DELETE THIS LINE -- make depend needs it
